### ISSUE TITLE
Resize artifacts

### ISSUE THREAD

**Issue by dkovalkov** [nfnt/resize#26]
Thank you for this package. I downsized this image
https://www.dropbox.com/s/fs91vfx1y4khymv/button_cost_up.png?dl=0
and got artifacts
https://www.dropbox.com/s/0me0559p7nl3yf5/test_resized.png?dl=0

with all interpolations except NearestNeighbor.
How to avoid it?

**Comment by nfnt** [comment]
The alpha channel of the image seems to be causing the artifacts. I could reproduce the issue and will look into it tomorrow.

**Comment by dkovalkov** [comment]
Thanks

**Comment by nfnt** [comment]
It seems that the artifacts you are seeing could be due to a bug in the `image/png` package. I reported the issue at https://github.com/golang/go/issues/10191

**Comment by nfnt** [comment]
Nope, it's not a bug in `image/png`, it's caused by a wrong usage of `image/color`. I'll try to fix it asap.

**Comment by dkovalkov** [comment]
Great!

**Comment by nfnt** [comment]
The artifacts should be gone starting with f2d1b73023c55bdfb4fa2ed385d2bec95bce3692. Please test this with your images, it was kinda hard to create good test cases for that one.

**Comment by dkovalkov** [comment]
It looks great! Thank you.
