### ISSUE TITLE
Runtime panic when trying to resize 4:1:1 YCbCr image

### ISSUE THREAD

**Issue by carl-mastrangelo** [nfnt/resize#37]
I got a runtime panic when trying to resize a jpeg image that has 4x1 Chroma Subsampling, aka. image.YCbCrSubsampleRatio411.  In ycc.go, it seems the default is 444 if no other sample is matched, which causes an index out of range panic.

I have a reproducible test program and image, if desired.

**Comment by carl-mastrangelo** [comment]
Friendly ping.  This represents a DoS vector when the picture comes from an untrusted source.  In my case it is creating a thumbnail from a user uploaded picture.

**Comment by nfnt** [comment]
Fixed by #57.
