### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by thellimist** [nfnt/resize#40]
Can you have a benchmark for the algorithms.

**Comment by nfnt** [comment]
Sure, you can use `go test -bench .` in the source directory to run some internal benchmarks. They try to simulate a real-world resize scenario and are mostly useful to see if changes to the source code affect the algorithms' performance somewhat. There are probably some projects that compare the performance of this package to other scaling packages, but you'd have to search for that.

**Comment by matrixik** [comment]
Here: https://github.com/fawick/speedtest-resize
