### ISSUE TITLE
1px black border after resize png images

### ISSUE THREAD

**Issue by grr89** [nfnt/resize#45]
maybe and for different image formats

**Comment by nfnt** [comment]
Can you provide more information about the input image and the resize parameters? Ideally would be the actual input image as well as some information on how you call `resize.Resize`. Also okay would be the size (in pixels) of the input and output images and whether the input image contains an alpha channel, and if it's a JPG or PNG or something else. Thanks!

**Comment by nfnt** [comment]
Closing this as "Can't reproduce". Feel free to re-open when more informations can be provided.
