### ISSUE TITLE
Transparent images cause black coloring

### ISSUE THREAD

**Issue by karlbright** [nfnt/resize#47]
I assume this is related to #45, but have done some more looking in to it. Currently this seems to be an issue with transparent PNGs on testing, and is present with any interpolation function but "Nearest Neighbor".

In both the examples below the image is being read in with `image.Decode` and resized with `resize.Thumbnail(uint(*width), uint(*height), img, methods[*method])`, before using `image.Encode` to a file.

For reference, the source image I am using, and settings on save are the following:

## Original
![test](https://cloud.githubusercontent.com/assets/20490/16294180/d190441e-3951-11e6-9bbe-275ceb9d1ad5.png)
![screen shot 2016-06-23 at 2 47 51 pm](https://cloud.githubusercontent.com/assets/20490/16294181/d2e58626-3951-11e6-8d32-0586aa6bbe64.png)

Along with the result of the various resize methods provided below. Resizing from the original 500x500 size to 100x100.

## Nearest
![out](https://cloud.githubusercontent.com/assets/20490/16294212/fa01c09e-3951-11e6-8ea0-20be60e8c8fe.png)

## Bicubic
![out](https://cloud.githubusercontent.com/assets/20490/16294218/015b27b8-3952-11e6-8d55-7aca906a7752.png)

## Bilinear
![out](https://cloud.githubusercontent.com/assets/20490/16294229/0c950388-3952-11e6-929b-883ae720b8f2.png)

## Mitchell
![out](https://cloud.githubusercontent.com/assets/20490/16294234/128ee9f2-3952-11e6-86c1-f74c1b303747.png)

## Lanczos2
![l](https://cloud.githubusercontent.com/assets/20490/16294240/1ba31f86-3952-11e6-88ca-a6c009872f9e.png)

## Lanczos3
![l](https://cloud.githubusercontent.com/assets/20490/16294242/1f405b68-3952-11e6-875f-3c46c4a3f539.png)

---

This example is even more obvious and unpredictable when you have something like anti-aliased text.

## Original
![test](https://cloud.githubusercontent.com/assets/20490/16294297/6afd5632-3952-11e6-8faf-23455293d315.png)

Then resizing down to 100px width.

## Nearest
![out](https://cloud.githubusercontent.com/assets/20490/16294336/9aca8a74-3952-11e6-9cec-36cb718799ab.png)

## Bicubic
![out](https://cloud.githubusercontent.com/assets/20490/16294332/97e71dc2-3952-11e6-9684-6581e9141be0.png)

## Bilinear
![out](https://cloud.githubusercontent.com/assets/20490/16294330/946f919c-3952-11e6-9a92-bddf8eed34de.png)

## Mitchell
![out](https://cloud.githubusercontent.com/assets/20490/16294327/9078ab64-3952-11e6-9ed7-371d93b8b81c.png)

## Lanczos2
![out](https://cloud.githubusercontent.com/assets/20490/16294322/8c1a34e8-3952-11e6-8894-c639d1c5c865.png)

## Lanczos3
![out](https://cloud.githubusercontent.com/assets/20490/16294317/88177e5a-3952-11e6-955b-aa6960c10e85.png)

**Comment by nfnt** [comment]
Thanks for the detailed description! Resizing with alpha channels is challenging (and tough to test), these details are really appreciated. I'll try to look into this as soon as I'll have some cycles. Unfortunately this won't be in the next week, but I hope to find some time after that.

**Comment by Sky-Li** [comment]
I met a similar issue, and the interpolation function "Nearest Neighbor" also transparent the png to black coloring.
And BTW, I find all those PNG image are converted to JPG image.
So did I use the function in the wrong way? Hope to get you help!

## Here is my code:
`

        // SaveImageThumbnail save image thumbnail by file
        func SaveImageThumbnail(file multipart.File, fileName string) (*s3manager.UploadOutput, error) {
                if _, err := file.Seek(0, 0); err != nil {
                         log.Error("filename: %s, error: %v", fileName, err)
                }
                if srcImage, _, err := image.Decode(file); err == nil {
		         thumbnail := resize.Thumbnail(300, 300, srcImage, resize.NearestNeighbor)
                         year, month, _ := time.Now().Date()
                         filePath := strings.Join([]string{strconv.Itoa(int(year)), strconv.Itoa(int(month)), fileName}, "/")
                         return S3.UploadThumbnail(thumbnail, filePath)
                } else {
                         log.Error("filename: %s, error: %v", fileName, err)
                         return nil, err
                }
        }
`

## Here is the resized PNG images:

### NearestNeighbor:
![test_neaerestneighbor](https://user-images.githubusercontent.com/9549072/30842722-e4697338-a2b6-11e7-95a1-acc92138688f.jpg)

### Lanczos3:
![test_lanczos3](https://user-images.githubusercontent.com/9549072/30842787-69a33804-a2b7-11e7-8298-90a0a6ded258.jpg)
