### ISSUE TITLE
panic: index out of range when resize some picture

### ISSUE THREAD

**Issue by JunyiHe** [nfnt/resize#49]
github.com/nfnt/resize.imageYCbCrToYCC(0xc84cacfc80, 0x14)
	D:/Workplace/src/github.com/nfnt/resize/ycc.go:220 +0x821
github.com/nfnt/resize.resizeNearest(0xc8, 0x7d, 0x4023333333333333, 0x4023333333333333, 0x7fb757e33348, 0xc84cacfc80, 0x0, 0x0, 0x0)
	D:/Workplace/src/github.com/nfnt/resize/resize.go:415 +0x6b9d
github.com/nfnt/resize.Resize(0xc8, 0x7d, 0x7fb757e33348, 0xc84cacfc80, 0x0, 0x0, 0x0)
	D:/Workplace/src/github.com/nfnt/resize/resize.go:96 +0x416
github.com/nfnt/resize.Thumbnail(0xc8, 0x7d, 0x7fb757e33348, 0xc84cacfc80, 0x0, 0x0, 0x0)
	D:/Workplace/src/github.com/nfnt/resize/thumbnail.go:54 +0x15f

please help fix this problem :)

**Comment by matrixik** [comment]
Hi, please provide picture that trigger this behaviour.

**Comment by JunyiHe** [comment]
sorry, I can't found this picture...

**Comment by nfnt** [comment]
This might be #37, but that's hard to say without an input image. Please provide additional information for us to be able to reproduce this issue.

**Comment by nfnt** [comment]
Closing this as non-reproducible.
