### ISSUE TITLE
ycc.go:126: undefined: image.YCbCrSubsampleRatio440

### ISSUE THREAD

**Issue by Kirkis** [nfnt/resize#50]
Hi,

While trying out smlr cf. "link 1" (which uses butteraugli cf. "link 2"), I encountered this error:
```
$ go get github.com/jasonmoo/smlr
# github.com/nfnt/resize
/usr/lib/go/src/pkg/github.com/nfnt/resize/ycc.go:126: undefined: image.YCbCrSubsampleRatio440
/usr/lib/go/src/pkg/github.com/nfnt/resize/ycc.go:196: undefined: image.YCbCrSubsampleRatio440
```

Please tell me if you need me to provide more information.

[1] https://github.com/jasonmoo/smlr
[2] https://github.com/google/butteraugli

**Comment by nfnt** [comment]
That's #37.
